TypeToolkit/DontExpectUnexpectedNil:
  Description: "Detects misuse of UnexpectedNilError (rescuing, raising, or asserting it)."
  Enabled: true
  VersionAdded: "0.1.0"

TypeToolkit/PreferNotNil:
  Description: "Replaces T.must assertions with Type Toolkit's not_nil! assertion."
  Enabled: true
  VersionAdded: "0.1.0"
